from fastapi import APIRouter, Depends
from app.core.dependencies import get_current_active_user
from app.services.ai.caption_service import caption_service
from app.services.ai.rate_limiter import check_ai_rate_limit
from app.schemas.ai.caption_schema import CaptionRequest, CaptionResponse
from app.schemas.common import SuccessResponse
from app.models.user import User

router = APIRouter()

@router.post("/gallery/caption", response_model=SuccessResponse[CaptionResponse])
async def ai_generate_caption(
    request: CaptionRequest,
    current_user: User = Depends(get_current_active_user),
):
    await check_ai_rate_limit(current_user.id, feature="captions", limit=10)

    caption_data = await caption_service.generate_caption(
        event_type=request.event_type,
        location=request.location,
        file_type=request.file_type,
        upload_context=request.upload_context or "",
    )

    return SuccessResponse(
        message="Photo caption generated by AI",
        data=CaptionResponse(**caption_data)
    )
