from fastapi import APIRouter, Depends
from app.core.dependencies import get_current_active_user
from app.services.ai.chat_service import chat_service
from app.services.ai.rate_limiter import check_ai_rate_limit
from app.schemas.ai.chat_schema import ChatSuggestRequest, ChatSuggestResponse
from app.schemas.common import SuccessResponse
from app.models.user import User

router = APIRouter()

@router.post("/chat/suggest-reply", response_model=SuccessResponse[ChatSuggestResponse])
async def ai_suggest_reply(
    request: ChatSuggestRequest,
    current_user: User = Depends(get_current_active_user),
):
    await check_ai_rate_limit(current_user.id, feature="chat", limit=30)

    suggestions_data = await chat_service.suggest_reply(
        last_message=request.last_message,
        sender_role=request.sender_role,
        conversation_context=request.conversation_context,
    )

    return SuccessResponse(
        message="Chat reply suggestions generated by AI",
        data=ChatSuggestResponse(**suggestions_data)
    )
