from fastapi import APIRouter, Depends
from app.core.dependencies import get_current_active_user, require_role
from app.services.ai.insights_service import insights_service
from app.services.ai.rate_limiter import check_ai_rate_limit
from app.schemas.ai.insights_schema import InsightsRequest, InsightsResponse
from app.schemas.common import SuccessResponse
from app.models.user import User

router = APIRouter()

@router.post("/dashboard/insights", response_model=SuccessResponse[InsightsResponse])
async def ai_earnings_insights(
    request: InsightsRequest,
    current_user: User = Depends(require_role("creator")),
):
    await check_ai_rate_limit(current_user.id, feature="insights", limit=5)

    insights_data = await insights_service.get_insights(request.stats)

    return SuccessResponse(
        message="Business earnings insights generated by AI",
        data=InsightsResponse(**insights_data)
    )
