from fastapi import APIRouter, Depends
from app.core.dependencies import get_current_active_user
from app.services.ai.pricing_service import pricing_service
from app.services.ai.rate_limiter import check_ai_rate_limit
from app.schemas.ai.pricing_schema import PriceSuggestRequest, PriceSuggestResponse
from app.schemas.common import SuccessResponse
from app.models.user import User

router = APIRouter()

@router.post("/booking/price-suggest", response_model=SuccessResponse[PriceSuggestResponse])
async def ai_suggest_price(
    request: PriceSuggestRequest,
    current_user: User = Depends(get_current_active_user),
):
    await check_ai_rate_limit(current_user.id, feature="pricing", limit=10)

    pricing_data = await pricing_service.suggest_price(
        event_type=request.event_type,
        duration_hours=request.duration_hours,
        city=request.city,
        creator_rate=request.creator_rate,
    )

    return SuccessResponse(
        message="Price suggestion generated by AI",
        data=PriceSuggestResponse(**pricing_data)
    )
