package com.capturo.app.premium

import android.content.Context
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import androidx.core.content.FileProvider
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Generates a booking-receipt PDF for the self-contained premium demo and
 * returns a shareable [Uri] (via the app's FileProvider) so it can be opened
 * from the chat thread the photographer sends it in.
 */
object PremiumReceipt {

    data class Details(
        val bookingId: String,
        val photographer: String,
        val customer: String,
        val event: String,
        val date: String,
        val time: String,
        val location: String,
        val pkg: String,
        val paymentMethod: String,
        val total: Int
    )

    /** File name used for the receipt (safe for FileProvider / chat display). */
    fun fileNameFor(d: Details) = "Capturo_Receipt_${d.bookingId}.pdf"

    fun generate(context: Context, d: Details): Uri {
        val doc = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 @72dpi
        val page = doc.startPage(pageInfo)
        val c = page.canvas

        val gold = Color.parseColor("#C8A24B")
        val dark = Color.parseColor("#1A1A1A")
        val grey = Color.parseColor("#666666")

        val title = Paint().apply { color = dark; textSize = 26f; typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD); isAntiAlias = true }
        val brandSub = Paint().apply { color = gold; textSize = 12f; isAntiAlias = true }
        val label = Paint().apply { color = grey; textSize = 12f; isAntiAlias = true }
        val value = Paint().apply { color = dark; textSize = 14f; typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD); isAntiAlias = true }
        val line = Paint().apply { color = Color.parseColor("#E0E0E0"); strokeWidth = 1f }
        val bandPaint = Paint().apply { color = gold }
        val bandText = Paint().apply { color = Color.WHITE; textSize = 16f; typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD); isAntiAlias = true }

        // Header band
        c.drawRect(0f, 0f, 595f, 90f, bandPaint)
        c.drawText("CAPTURO", 40f, 45f, Paint(bandText).apply { textSize = 24f })
        c.drawText("Capture Moments. Book Memories.", 40f, 68f, Paint().apply { color = Color.WHITE; textSize = 11f; isAntiAlias = true })

        c.drawText("Booking Receipt", 40f, 135f, title)
        c.drawText("Payment successful — thank you for your booking!", 40f, 158f, brandSub)

        var y = 200f
        fun row(l: String, v: String) {
            c.drawText(l.uppercase(Locale.getDefault()), 40f, y, label)
            c.drawText(v.ifBlank { "—" }, 40f, y + 20f, value)
            y += 52f
            c.drawLine(40f, y - 18f, 555f, y - 18f, line)
        }

        row("Booking ID", d.bookingId)
        row("Photographer", d.photographer)
        row("Booked By", d.customer)
        row("Event Type", d.event)
        row("Date", d.date)
        row("Time Slot", d.time)
        row("Location", d.location)
        row("Package", d.pkg)
        row("Payment Method", d.paymentMethod)

        // Total band
        y += 10f
        c.drawRect(40f, y, 555f, y + 60f, Paint().apply { color = Color.parseColor("#FBF4E4") })
        c.drawText("TOTAL PAID", 60f, y + 37f, Paint(label).apply { textSize = 13f })
        val totalText = "₹" + "%,d".format(d.total)
        c.drawText(totalText, 555f - value.measureText(totalText).coerceAtLeast(120f) - 20f, y + 40f,
            Paint(value).apply { textSize = 22f; color = gold })

        // Footer
        val stamp = SimpleDateFormat("d MMM yyyy, h:mm a", Locale.getDefault()).format(Date())
        c.drawText("Generated on $stamp", 40f, 800f, Paint(label).apply { textSize = 10f })
        c.drawText("This is a demo receipt generated by the Capturo app.", 40f, 816f, Paint(label).apply { textSize = 10f })

        doc.finishPage(page)

        val dir = File(context.cacheDir, "receipts").apply { mkdirs() }
        val file = File(dir, fileNameFor(d))
        file.outputStream().use { doc.writeTo(it) }
        doc.close()

        return FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
    }
}
